---
before_script:
  - set +o pipefail
  - bundle config set deployment 'true'
  - bundle config set path 'vendor/bundle'

stages:
  - build

.build_fastlane:
  allow_failure: false
  stage: build
  when: manual
  environment:
    name: accept
  script:
    - "bundle install --jobs 3 --retry 3"
    - "bundle exec fastlane ios $FASTLANE_COMMAND environment:$ENVIRONMENT target:$TARGET_NAME --verbose"
  tags:
    - ios
  artifacts:
    expire_in: 2 weeks
    paths:
      - build/*.ipa
      - build/*.dSYM.zip

build-accept:
  extends: .build_fastlane
  variables:
    ENVIRONMENT: "Accept"
    FASTLANE_COMMAND: "build_adhoc"

build-test:
  extends: .build_fastlane
  variables:
    ENVIRONMENT: "Test"
    FASTLANE_COMMAND: "build_adhoc"

build-production:
  extends: .build_fastlane
  variables:
    ENVIRONMENT: "Production"
    FASTLANE_COMMAND: "build_adhoc"

build-release:
  extends: .build_fastlane
  variables:
    ENVIRONMENT: "Production"
    FASTLANE_COMMAND: "release"